# Generated by Django 3.0.7 on 2021-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('performer', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
