# Generated by Django 3.0.7 on 2021-04-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='performer',
            new_name='performers',
        ),
    ]
